### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by matrixxun** [vanniktech/gradle-dependency-graph-generator-plugin#67] opened 2018-08-13 10:10 UTC
Hi, vanniktech
when I use 0.5.0 version in my project in root build.gradle, it build failed. please see the log:

``` java FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateDependencyGraph'.
> For input string: "152-release"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
1 actionable task: 1 executed
18:08:09: Task execution finished 'generateDependencyGraph'.

**Comment by vanniktech** [comment] 2018-08-13 10:16
Dupe of #64

The workaround for now is:

```gradle
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "guru.nidi:graphviz-java:0.5.3"
    classpath "com.vanniktech:gradle-dependency-graph-generator-plugin:0.5.0"
  }
}
```

**Closed by vanniktech** 2018-08-13 10:16 UTC
