### ISSUE TITLE
For input string: "242-release" 

### ISSUE THREAD

**Issue by ff-frida** [vanniktech/gradle-dependency-graph-generator-plugin#117] opened 2021-03-24 09:37 UTC
```
> Task :generateDependencyGraph FAILED
1 actionable task: 1 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateDependencyGraph'.
> For input string: "242-release"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
17:35:05: Task execution finished 'generateDependencyGraph'.


```

```

mavenCentral()
        classpath "com.vanniktech:gradle-dependency-graph-generator-plugin:0.5.0"
apply plugin: "com.vanniktech.dependency.graph.generator"
```

click：generateDependencyGraph task

**Comment by vanniktech** [comment] 2021-03-24 09:44
Dupe of #96

**Closed by vanniktech** 2021-03-24 09:44 UTC
