### ISSUE TITLE
Multiproject builds are not supported

### ISSUE THREAD

**Issue by tfedyanin** [vanniktech/gradle-dependency-graph-generator-plugin#49] opened 2018-05-19 06:46 UTC
Hi, thank you for this awesome tool!

I have a problem, my project has stucture:
root
|
-- subproject1

I apply plugin in root project, but graph generated for subproject1 only. How to fix this issue?

**Comment by vanniktech** [comment] 2018-05-19 06:57
That's working as intended since the root project has no external dependencies

**Comment by vanniktech** [comment] 2018-05-20 21:18
I've also got a test for a multi project https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/aa910ccfc0ede56352897c7231f61d5c0eed6bb8/src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPluginTest.kt#L104

Hence I'm closing this. If you come up with a test case that fails let me know.

**Closed by vanniktech** 2018-05-20 21:18 UTC
