### ISSUE TITLE
broken in gradle 7.0

### ISSUE THREAD

**Issue by NikkyAI** [vanniktech/gradle-dependency-graph-generator-plugin#124] opened 2021-06-15 13:41 UTC
when runnign with gradle `7.0.2` the task breaks the the following message

```
A problem was found with the configuration of task ':generateDependencyGraph' (type 'DependencyGraphGeneratorTask').
  - Type 'com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorTask' property 'generator' is missing an input or output annotation.
```

**Comment by tdp0516** [comment] 2021-06-18 16:57
I believe this is a duplicate of this issue: https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/issues/121

It appears to have been fixed but not released yet.

**Comment by vanniktech** [comment] 2021-06-19 06:47
Yes true.

**Closed by vanniktech** 2021-06-19 06:47 UTC

**Comment by kuldeepsidhu88** [comment] 2022-12-03 12:46
@vanniktech Has this been released? I am still getting this error in gradle 7.4
